### ISSUE TITLE
synced block 이 제대로 인식되지 않는 문제

### ISSUE THREAD

**Issue by ProtossDragoon** [jmjeon94/N2T#2]
안녕하세요, 블로그에서 보고 한번 사용해보기 위해 돌려보고 있었습니다. 
synced block 을 처리하는 경우 잘 동작하지 않는 문제가 있었습니다.

https://github.com/jmjeon94/N2T/blob/b089c83f96284cb17b888d3575294c1cb2bb3ffc/main.py#L122-L126

이 부분에서 synced block 내부에 들어 있는 코드블럭을 전혀 인식하지 못했습니다.

synced block 내부의 이미지를 처리하는 도중에도 비슷한 문제가 발생했습니다.

**Comment by jmjeon94** [comment]
현재 unofficial python api 로는 sync block이 구현이 안되어있는 것 같습니다. 다시 한 번 확인후에 가능하면 수정하겠습니다!

**Comment by jmjeon94** [comment]
안녕하세요 말씀하신 에러는 sync block의 문제가 아니라 
코드블록이 다른 블록의 하위블록으로 들어가는 경우에 인식이 안 된 것 같습니다.

https://github.com/jmjeon94/N2T/commit/056b2928ceeeb58bc48a1266f060565c1d0bbdb5

위처럼 코드를 수정하였으니 다시 동작 확인해주시면 감사하겠습니다.
이미지 처리에러 정확히 어떤 에러인지 에러메시지를 알 수 있을까요?

**Comment by ProtossDragoon** [comment]
> 안녕하세요 말씀하신 에러는 sync block의 문제가 아니라 코드블록이 다른 블록의 하위블록으로 들어가는 경우에 인식이 안 된 것 같습니다.
> 
> [056b292](https://github.com/jmjeon94/N2T/commit/056b2928ceeeb58bc48a1266f060565c1d0bbdb5)
> 
> 위처럼 코드를 수정하였으니 다시 동작 확인해주시면 감사하겠습니다. 이미지 처리 에러는 정확히 어떤 에러인지 에러메시지를 알 수 있을까요?

https://github.com/jmjeon94/N2T/commit/056b2928ceeeb58bc48a1266f060565c1d0bbdb5#r75625446
https://github.com/jmjeon94/N2T/commit/056b2928ceeeb58bc48a1266f060565c1d0bbdb5#commitcomment-75625993
https://github.com/jmjeon94/N2T/commit/056b2928ceeeb58bc48a1266f060565c1d0bbdb5#commitcomment-75626144
